version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: node:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # Fallback to use the latest cache if no exact match is found
            - dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run: yarn build

  test:
    docker:
      - image: node:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # Fallback to use the latest cache if no exact match is found
            - dependencies-
      - run: yarn --cache-folder .cache/yarn test:ci

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
